#include "stm32f4xx.h"

#define TIM2EN_CLK			(1U<<0)
#define CR1_CEN				(1U<<0)
#define OC_TOGGLE			(1U<<4) | (1U<<5)
#define CCER_CC1E			(1U<<0)

#define GPIOAEN				(1U<<0)
#define	TIM3EN_CLK			(1U<<1)
#define TIM3_CC1E			(1U<<0)

void tim2_1hz_init(void)
{
	//ENABLE CLOCK ACCESS TO APB1
	RCC->APB1ENR |= TIM2EN_CLK;

	//SET THE PRESCALER VALUE
	TIM2->PSC = 1600 - 1; // 16MHz/1600Hz

	//SET THE AUTORELOAD VALUE
	TIM2->ARR = 10000 - 1;

	//CLEAR COUNTER
	TIM2->CNT = 0x00;

	//ENABLE TIMER
	TIM2->CR1 |= CR1_CEN;
}

void tim2_pa5_output_compare(void)
{
	//ENABLE CLOCK ACCESS TO GPIOA
	RCC->AHB1ENR |= GPIOAEN;

	//SET PA5 MODE TO ALTERNATE MODE
	GPIOA->MODER |=  (1U<<11);
	GPIOA->MODER &=~ (1U<<10);

	//SET PA5 ALTERNATE FUNCTION TYPE TO TIM2_CH1
	GPIOA->AFR[0] |= (1U<<20);
	GPIOA->AFR[0] &=~ (1U<<21);
	GPIOA->AFR[0] &=~ (1U<<22);
	GPIOA->AFR[0] &=~ (1U<<23);

	//ENABLE CLOCK ACCESS TO APB1
	RCC->APB1ENR |= TIM2EN_CLK;

	//SET THE PRESCALER VALUE
	TIM2->PSC = 1600 - 1; // 16MHz/1600Hz

	//SET THE AUTORELOAD VALUE
	TIM2->ARR = 10000 - 1;

	//SET OUTPUT COMPARE TOGGLE MODE
	TIM2->CCMR1 = OC_TOGGLE;

	//ENABLE TIM2 CH1 IN COMPARE MODE
	TIM2->CCER |= CCER_CC1E;

	//CLEAR COUNTER
	TIM2->CNT = 0x00;

	//ENABLE TIMER
	TIM2->CR1 |= CR1_CEN;
}

void tim3_pa6_input_capture(void)
{
	//TIM3 ON PA6 - AF02
	//ENABLE CLOCK ACCESS TO GPIOA
	RCC->AHB1ENR |= GPIOAEN;

	//SET PA6 AS ALTERNTE FUNNCTION
	GPIOA->MODER |=  (1U<<13);
	GPIOA->MODER &=~ (1U<<12);

	//SET PA6 AS AF02 (TIMER3)
	GPIOA->AFR[0] |= (1U<<25);

	//ENABLE CLOCK FOR TIM3 (APB1)
	RCC->APB1ENR |= TIM3EN_CLK;

	//SET PRESCALER
	TIM3->PSC = 16000 - 1;

	//SET CH1 TO CAPTURE FOR EVERY EDGE
	TIM3->CCMR1 |=  (1U<<0);
	TIM3->CCMR1 &=~ (1U<<1);

	//SET CH1 TO CAPTURE TO RISING EDGE
	TIM3->CCER = TIM3_CC1E;

	//ENABLE TIM3
	TIM3->CR1 = TIM3_CC1E;

}
