#include "stm32f4xx.h"
#include "tim.h"

#define TIM2EN_CLK			(1U<<0)
#define CR1_CEN				(1U<<0)
#define OC_TOGGLE			(1U<<4) | (1U<<5)
#define CCER_CC1E			(1U<<0)

#define GPIOAEN					(1U<<0)

void tim2_1hz_init(void)
{
	//ENABLE CLOCK ACCESS TO APB1
	RCC->APB1ENR |= TIM2EN_CLK;

	//SET THE PRESCALER VALUE
	TIM2->PSC = 1600 - 1; // 16MHz/1600Hz

	//SET THE AUTORELOAD VALUE
	TIM2->ARR = 10000 - 1;

	//CLEAR COUNTER
	TIM2->CNT = 0x00;

	//ENABLE TIMER
	TIM2->CR1 |= CR1_CEN;
}

void tim2_pa5_output_compare(void)
{
	//ENABLE CLOCK ACCESS TO GPIOA
	RCC->AHB1ENR |= GPIOAEN;

	//SET PA5 MODE TO ALTERNATE MODE
	GPIOA->MODER |=  (1U<<11);
	GPIOA->MODER &=~ (1U<<10);

	//SET PA5 ALTERNATE FUNCTION TYPE TO TIM2_CH1
	GPIOA->AFR[0] |= (1U<<20);
	GPIOA->AFR[0] &=~ (1U<<21);
	GPIOA->AFR[0] &=~ (1U<<22);
	GPIOA->AFR[0] &=~ (1U<<23);

	//ENABLE CLOCK ACCESS TO APB1
	RCC->APB1ENR |= TIM2EN_CLK;

	//SET THE PRESCALER VALUE
	TIM2->PSC = 1600 - 1; // 16MHz/1600Hz

	//SET THE AUTORELOAD VALUE
	TIM2->ARR = 10000 - 1;

	//SET OUTPUT COMPARE TOGGLE MODE
	TIM2->CCMR1 = OC_TOGGLE;

	//ENABLE TIM2 CH1 IN COMPARE MODE
	TIM2->CCER |= CCER_CC1E;

	//CLEAR COUNTER
	TIM2->CNT = 0x00;

	//ENABLE TIMER
	TIM2->CR1 |= CR1_CEN;
}
